Remove Rails gem dependency
mrhardikjoshi/graphiti-rails pull request #1
Opened 2020-06-04 13:51 UTC by mrhardikjoshi

Problem:
Rails 5 was added as a dependency in gemspec. This restricted use of `graphiti-rails` gem in project where whole rails gem suit was used.

If some project only uses ActionPack and `ActiveSupport` then including `graphiti-rails` results in loading all of the Rails gem suit (`ActiveRecord` etc.)

Solution:
Since graphiti-rails is dependant on 1) `actionpack` 2) `activesupport` and 3) `railties` only we can remove `rails` from gemspec and add these three gems as dependancy

2020-06-16 20:59 UTC, klobuczek requested changes
The fewer changes the higher likelihood of acceptance.

2020-06-16 20:59 UTC, klobuczek commented on graphiti-rails.gemspec
> +  spec.add_dependency "actionpack", ">= 5.0"
```suggestion
```

2020-06-16 20:59 UTC, klobuczek commented on lib/graphiti/rails/railtie.rb
> +        if ::ActionPack::VERSION::MAJOR >= 5
```suggestion
        if ::Rails::VERSION::MAJOR >= 5
```

2020-06-16 21:00 UTC, klobuczek commented
make a PR against the upstream

2020-06-18 14:31 UTC, mrhardikjoshi commented
Closing this as I have created one against the original repo

2020-06-18 14:31 UTC, closed without merging